### ISSUE TITLE
ExcelExport: Step1

### ISSUE THREAD

**Issue by ManCon25** [ManCon25/EngDbIssuesOnly#23]
Export der Daten eines Views auf eine Excel-Vorlage:

Vorbereitungen: Die Excel Vorlagedateien müssen auf dem Server hinterlegt sein.

Neuer Export Button, der
1. Das richtige Template auswählt und öffnet,
2. Die Daten entsprechend der Spaltenbezeichner in das Template schreibt.
3. Die Datei als Download zur Verfügung stellt.

**Comment by ThisIsKickZ** [comment]
Export abgeschlossen
